server:
    port: 8081

spring:

  main:
    allow-circular-references: true

  application:
    name: lanchonete

    # H2 configuration
    datasource:
      #url: jdbc:h2:mem:lanchonetedb
      url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      #driverClassName: org.h2.Driver
      driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
   # h2:
   #   console:
   #     enabled: true
   #     path: /h2-console
    jpa:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        show-sql: true
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
      properties:
        hibernate:
          format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true

production:
  api:
    get-url: "http://a2774f61a5b354a459d3f99b939f7009-1239291071.us-east-1.elb.amazonaws.com/{ORDER-ID}/status"
    change-url: "http://a2774f61a5b354a459d3f99b939f7009-1239291071.us-east-1.elb.amazonaws.com/{ORDER-ID}/status"

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs

# Swagger
  swagger-ui:
    path: /swagger-ui.html

